plugins {
    id 'com.android.application'
}
dependencies {
    implementation 'com.squareup.okhttp3:okhttp:3.12.13'
    implementation 'org.conscrypt:conscrypt-android:2.5.3'
    implementation 'androidx.browser:browser:1.6.0'
}

android {
    namespace 'org.CreadoresProgram.CreaProDroid'
    compileSdkVersion 28

    defaultConfig {
        minSdkVersion 16
        targetSdkVersion 28
        versionCode 6
        versionName "1.4.0-beta"
    }
    signingConfigs {
        debug {
            storeFile file('CreaProDroid.keystore')
            storePassword System.getenv("CREAPRODROIDKEYCONTREAPP")
            keyAlias "CreaProDroidkey"
            keyPassword System.getenv("CREAPRODROIDKEYCONTREAPP")
        }
    }
    buildTypes {
        debug {
            signingConfig signingConfigs.debug
        }
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}
